### ISSUE TITLE
Cider refuses to open window

### ISSUE THREAD

**Issue by cmdrneon** [ciderapp/cider-releases#1]
Just installed Cider as an avid Apple Music user and was having issues opening it.

```
[08:38:10.373] [info]  From here can you check for real changes, the initial scan has been completed.
[08:38:10.374] [info]  Cider client port: 9000
[08:38:10.376] [info]  Cider remote port: 6942
[08:38:10.379] [info]  remote broadcasted
[08:38:10.465] [error] Error: Failed to lookup view "main" in views directory "/opt/Cider/resources/app.asar/src/renderer/views"
    at Function.render (/opt/Cider/resources/app.asar/node_modules/express/lib/application.js:597:17)
    at ServerResponse.render (/opt/Cider/resources/app.asar/node_modules/express/lib/response.js:1039:7)
    at /opt/Cider/resources/app.asar/src/main/base/browserwindow.ts:423:17
    at Layer.handle [as handle_request] (/opt/Cider/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/Cider/resources/app.asar/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/opt/Cider/resources/app.asar/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/opt/Cider/resources/app.asar/node_modules/express/lib/router/layer.js:95:5)
    at /opt/Cider/resources/app.asar/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/opt/Cider/resources/app.asar/node_modules/express/lib/router/index.js:346:12)
    at next (/opt/Cider/resources/app.asar/node_modules/express/lib/router/index.js:280:10)

```
I'm using Debian 11 (bullseye), and an Nvidia GPU with proprietary drivers. Everything above the error seems to be standard launch operation.

**Comment by cmdrneon** [comment]
Oh jeez, just realized i forgot to mention the app version.
I'm using `1.4.5-beta-2212`

**Comment by quacksire** [comment]
We do not monitor this repository for issues

Please open an issue on the main repository.
https://github.com/ciderapp/Cider/issues/new/choose
